# Index

# 01 : Numpy ?

- Numerical Python  

- 기능
    - 행렬과 행렬연산을 위해 도와주는 Python Pakage
        - 파이썬의 고성능 과학 계산용 패키지
        - Matrix, vector, array 연산의 표준  

- 특징
    - 일반 List에 비해 연산이 빠르고 , 메모리 효율적
    - 반복문 없이 데이터 배열에 대한 처리를 지원
    - 선형대수와 관련된 다양한 기능 제공
    - C , C++, 포트란 등의 언어에서도 지원  

- 예시
    - 수식
        > $2x_1 + 2x_2 + \;x_3 = 9 \\$  
        > $2x_1 + \;x_2 + 2x_3 = 6 \\$  
        > $\;x_1 - \;x_2 + 2x_3 = 5 \\$  
    - 행렬
        > $\begin{bmatrix}2 & 2 & 1 & 9 \\ 2 & -1 & 2 & 6 \\ 1 & -1 & 2 & 5 \end{bmatrix}$  
    - python 코드
        > coefficient_matrix = [[2,2,1], [2,-1,2], [1,-1,2]]  
        > constant_vector = [9,6,5]  
    - Numpy
        > import numpy as np  
        > coefficient_array = np.array([[2,2,1], [2,-1,2], [1,-1,2]])  
        > const_array = np.array([9,6,5])  

# 02 : 호출 / 생성 / dtype

- 호출
    > np.array(  )
    >> $\rightarrow \quad$ ndarray  

- dtype
    - 하나의 데이터 type만 지정가능 (list 와의 차이점)
        - dynamic typing 지원 (X)

## -01 : array creation

- numpy 는 np.array 함수를 활용 배열을 생성함 -> ndarray
- numpy 는 하나의 데이터 type만 배열에 넣을 수 있음
    - List 와 가장 큰 차이점 -> dtnamic typing not supported  
- C 의 Array 를 사용하여 배열을 생성함

### _01 : numpy 호출

In [1]:
import numpy as np

### _02 : array 생성

In [2]:
a = [1,2,3,4,5]
b = [5,4,3,2,1]

In [5]:
a = np.array(a, int)    # dtype 선언
a

array([1, 2, 3, 4, 5])

In [9]:
test_array = np.array(['1', '4', 5.0, 8], float)

print(test_array, type(test_array))
print(type(test_array[3]))

[1. 4. 5. 8.] <class 'numpy.ndarray'>
<class 'numpy.float64'>


### _03 : Python 과 Numpy 의 차이점

In [ ]:
a = [1,2,3,4,5]
b = [5,4,3,2,1]

In [15]:
# Python

a[0] is b[-1]
    #   직접적인 원소 비교가능

False

In [16]:
# Numpy

ar_a = np.array(a)
ar_b = np.array(b)

print(ar_a[0] is ar_b[-1])
print(ar_a[1] is ar_b[-2])
print(ar_a[1].tolist() is ar_b[-2].tolist())
    # 직접적인 원소 비교가 불가능 하다
        # 원리는 잘 이해가 안감

False
False
True


### _04 : 기타 numpy 명령어

- shape : numpy array 의 dimension 구성을 반환
- dtype : numpy array 의 데이터 type 을 반환
- array Rank(shape) 에 따른 이름

    | Rank | Name | Example | shape |  
    |-|-|-|-|  
    | 0 | scalar | 7 | none |  
    | 1 | vector | [10, 10] | (2,) |  
    | 2 | matrix | [[10, 10], [15, 15]] | (2,2) |  
    | 3 | 3-tensor | [[[1, 5, 9], [2, 6, 10]], [[3, 7, 11], [4, 8, 12]]] | (3,2,2) |  
    | n | n-tensor | $\cdots$ | (col, row, depth, 4th-d, $\cdots$ )  

#### array type

In [19]:
test_array = np.array([1,4,5,'8'], float) # string type 데이터를 입력해도 데이터 타입을 지정한다면 변경가능

print(test_array)
print(type(test_array[3]))
print(test_array.dtype)         # array 전체의 데이터 type 을 반환
print(test_array.shape)         # array 의 shape을 반환

[1. 4. 5. 8.]
<class 'numpy.float64'>
float64
(4,)


In [24]:
c = [[1,1], [1,1], [1,1]]
ar_c = np.array(c)

print(ar_c.shape)
print(ar_c)

(3, 2)
[[1 1]
 [1 1]
 [1 1]]


#### array shape

In [25]:
vector = [1, 2, 3, 4]
np.array(vector, int).shape

(4,)

In [26]:
matrix = [[1,2,5,8], [1,2,5,8], [1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [28]:
tensor_sample = [
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
]
a = np.array(tensor_sample, int)
a.shape

(4, 3, 4)

#### array Number of Dimension

In [29]:
a.ndim

3

#### array size

In [31]:
a.size
# 1d * 2d * 3d = 4 * 3 * 4 = 48

48

# 03 : reshape

- array 의 shape의 크기를 변경함, element의 갯수는 동일
    - 변경된 배열의 형태(size)가 맞지않지 않으면 reshape 불가 : Error 발생

        <img src='../image/numpy_01.jpeg' width=400>

## _01 : reshape(-1,n)

- size 를 기반으로 row 개수 선정

### -01 : reshape EX

In [32]:
test_matrix = [[1,2,3,4], [1,2,5,8]]
test_arr = np.array(test_matrix)

test_arr.shape

(2, 4)

In [36]:
print(test_arr)
print('-----')
print(test_arr.reshape(4,2))
print('-----')
print(test_arr.reshape(2,2,2))

[[1 2 3 4]
 [1 2 5 8]]
-----
[[1 2]
 [3 4]
 [1 2]
 [5 8]]
-----
[[[1 2]
  [3 4]]

 [[1 2]
  [5 8]]]


In [37]:
test_arr.reshape(1,-1) # (1,8)

array([[1, 2, 3, 4, 1, 2, 5, 8]])

In [38]:
test_arr.reshape(1, -1, 2) # (1,4,2)

array([[[1, 2],
        [3, 4],
        [1, 2],
        [5, 8]]])

## _02 : flatten

- 다차원 array 를 1차원 array 로 변환
    - .reshape(-1,) 과 동일한 기능  
    
        <img src='../image/numpy_02.jpeg' width=400>

In [42]:
print(test_arr.reshape(-1,))
print(test_arr.reshape(-1,).shape)
print(test_arr.flatten())

[1 2 3 4 1 2 5 8]
(8,)
[1 2 3 4 1 2 5 8]


# 04 : Indexing

- List 와 달리 이차원 배열에서 [n,n] 표기법을 제공함
    - [ $\cdots$ , 3d(depth), 2d(row), 1d(column) ]

## -01 : indexing EX

In [43]:
a = np.array([[1,2,3],[4.5,5,6]], int)
print(a)
print(a[0,0])   # 2x2 ndarray Indexing 방법 #1
print(a[0][0])   # 2x2 ndarray Indexing 방법 #1

a[0,0] = 12 # matrix 0,0 에 12 할당
print(a)

a[0][0] = 5 # matrix 0,0 dp 5 할당
print(a)


[[1 2 3]
 [4 5 6]]
1
1
[[12  2  3]
 [ 4  5  6]]
[[5 2 3]
 [4 5 6]]


# 05 : Slicing

- List 와 달리 행과 열 부분을 나눠서 scling 이 가능
- matrix 부분 집합을 추출할 때 유용함

## -01 : slcing EX

<img src='../image/numpy_03.jpeg' width=450>

In [44]:
a = np.array([[1,2,5,8], [1,2,5,8], [1,2,5,8], [1,2,5,8]], int)

a[:2,:]

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [45]:
print(a[:, 1:3])
print(a[:, 1:3].shape)

[[2 5]
 [2 5]
 [2 5]
 [2 5]]
(4, 2)


## -02 : slicng [start, end, step] EX

<img src='../image/numpy_04.jpeg' width=400>

- [:,::2] 의미

# 06 : Creation function (행렬 자동생성)

## -01 : np.arange(n)

In [47]:
import numpy as np

a = np.arange(100).reshape(10,10)
    # numpy ndarray를 arange를 통해 0에서 99까지 100개 항목 생성
    # reshape 를 통해 (100,) -> (10,10) 를 형변
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [50]:
a[:,-1]
    # row 전체해당
    # col 뒤에서 첫번째만 해당
        # 맨뒷줄 세로로 인자 뽑아서 출력

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

## -02 : arange 응용 (start, end, step)

In [57]:
a = np.arange(0, 5, 0.5)
    # start : 0 이상
    # end : 5 미만
    # step : 0.5 간격
        # 0 0.5 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 
print(a)

print(a.reshape(len(a),-1))

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[[0. ]
 [0.5]
 [1. ]
 [1.5]
 [2. ]
 [2.5]
 [3. ]
 [3.5]
 [4. ]
 [4.5]]


## -03 : zeros

In [60]:
np.zeros(shape=(10,), dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## -04 : ones

In [61]:
np.ones(shape=(10,), dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## -05 : empty

- shape 만 주어지고 비어있는 ndarray 생성  
    (memory initialization 이 되어있지 않음)

    - 이전에 사용된 공간을 공유하기 때문에 이상한 값들이 출력된다

In [67]:
np.empty(shape=(10,), dtype=int)

array([ 5764607523034234880, -1152921504328573065,                    5,
                          0,         137438953472,  7076615411713193529,
        7220445814180690221,  3256437007109140582,  3906367138444043876,
           1407376534157668])

In [64]:
np.empty(shape=(10,), dtype=np.int8)

array([  0,   0,   0,   0,   0,   0,   0,  80, 117,  96], dtype=int8)

In [68]:
np.empty(shape=(3,5))

array([[0.        , 0.        , 0.4472136 , 0.0531494 , 0.18257419],
       [0.4472136 , 0.2125976 , 0.36514837, 0.4472136 , 0.4783446 ],
       [0.54772256, 0.4472136 , 0.85039041, 0.73029674, 0.4472136 ]])

## -06 : something _like

- 기존 ndarray 의 shape 크기 만큼 1,0 또는 empty array 를 반환

In [70]:
test_matrix = np.arange(30).reshape(5,6)

np.ones_like(test_matrix)
    # tes_matrix 와 동일한 형태(5*6) 형태의 ones 매트릭스를 반환해 준다

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

## -07 : Identity

- 단위 행렬(i 행렬) 을 생성함

In [71]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [72]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## -08 : eye

- 대각선의 값이 1인 행렬, k값의 시작 Index의 변경이 가능

In [73]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [76]:
np.eye(3, 5, k=2)
    # 3x5 행렬 생성
    # 1값 시작점 [0,2] : k=2

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [78]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

## -09 : diag

- 대각 행렬의 값을 추출

In [81]:
matrix = np.arange(9).reshape(3,3)

print(matrix)
print('------')
print(np.diag(matrix))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
------
[0 4 8]


In [85]:
print(matrix)
print('------')
print(np.diag(matrix, k=-1))
    # k : start Index

[[0 1 2]
 [3 4 5]
 [6 7 8]]
------
[3 7]


## -10 : random sampling

- 데이터 분포에 따른 sampliung 으로 array 를 생성

    > 균등분포  
    >> np.random.uniform( 시작값 , 끝값 , 데이터_사이즈 )

    > 정규분포  
    >> np.random.normal( 중심값 , 범위 , 데이터_사이즈 )

In [86]:
# 균등분포 예시
np.random.uniform(0,1,10).reshape(2,5)

array([[0.98104322, 0.72826987, 0.49943975, 0.30469565, 0.12555862],
       [0.09770322, 0.74288559, 0.32159378, 0.95448161, 0.74365359]])

In [87]:
# 정규분포 예시
np.random.normal(0,1,10).reshape(2,5)

array([[ 0.01167861, -0.13391675,  1.8392519 ,  0.64112895,  0.35064126],
       [ 0.91850055,  0.39036093, -1.68139183,  0.63619759,  1.75350379]])

# 07 : Operation function

In [88]:
test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## -01 : sum (합)

In [89]:
sum(test_array)

55

In [90]:
test_array.sum()

55

## -02 : axis (계산 방향 축)

- 모든 operation function 을 실행할 때 기준이 되는 dimension 축

    <img src='../image/numpy_05.jpeg' width=200>   <img src='../image/numpy_06.jpeg' width=260>


    > | width | height | depth | $\cdots$ |  
    > | - | - | - | - |  
    > | col | row | - | $\cdots$ |  
    > | d1 | d2 | d3 | $\cdots$ |  
    > | $\cdots$ | axis2 | axis1 | axis0 |  



### _01 : axis EX_01

In [91]:
test_arr = np.arange(1,13).reshape(3,4)
test_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [92]:
test_arr.sum(axis=1), test_arr.sum(axis=0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

### _02 : axis EX_02

In [93]:
test_tensor = np.arange(1,37).reshape(3,4,3)
test_tensor

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [97]:
test_tensor.sum(axis=2) # 최초의 column 방향으로 덧셈

array([[  6,  15,  24,  33],
       [ 42,  51,  60,  69],
       [ 78,  87,  96, 105]])

In [96]:
test_tensor.sum(axis=1) # 최초의 row 방향으로 덧셈

array([[ 22,  26,  30],
       [ 70,  74,  78],
       [118, 122, 126]])

In [99]:
test_tensor.sum(axis=2) # 최초의 z축 방향(깊이-입체)으로 덧셈

array([[  6,  15,  24,  33],
       [ 42,  51,  60,  69],
       [ 78,  87,  96, 105]])

## -03 : mean (평균)

In [100]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [101]:
test_array.mean(), test_array.mean(axis=0)

(6.5, array([5., 6., 7., 8.]))

## -04 : std (표준편차)

In [102]:
test_array.std(), test_array.std(axis=0)

(3.452052529534663, array([3.26598632, 3.26598632, 3.26598632, 3.26598632]))

## -05 : mathematical functions

- 그 외에도 다양한 수학 연산자를 제공함 (np.something 호출)  

    - exponential  
        exp, expml, exp2, log, log10, loglp, log2, power, sqrt  

    - tringonometric  
        sin, cos, tan, acsin, arccos, arctan

    - hyperbolic  
        sinh, cosh, tanh, acshinh, arccosh, atctanh


# 08 : vstack & hstack

- numpy array 를 합치는 (붙이는) 함수

    <img src='../image/numpy_07.jpeg' width=300>

In [104]:
import numpy as np

a = np.array([1,2,3])
b = np.array([2,3,4])

np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [110]:
c = np.arange(1,4).reshape(len(c),-1)
d = np.arange(2,5).reshape(len(d),-1)

np.hstack((c,d))

array([[1, 2],
       [2, 3],
       [3, 4]])

# 09 : Concatenate (합치기)

- numpy array 를 합치는(붙이는) 함수

    <img src='../image/numpy_08.jpeg' width=320>

In [132]:
a = np.arange(1,4)
b = np.arange(2,5)

np.concatenate((a,b), axis=0)   # np.vstack((a,b))

array([1, 2, 3, 2, 3, 4])

In [144]:
c = np.arange(1,5).reshape(2,2)
print(c)

d = np.arange(5,7)
print(d)
d = d[np.newaxis, :]    # 값은 그대로 차원을 하나 더 추가
print(d)

np.concatenate((c, d.T), axis=1)    # np.hstack(c,d.T)

[[1 2]
 [3 4]]
[5 6]
[[5 6]]


array([[1, 2, 5],
       [3, 4, 6]])

# 10 : name[np.newaxis, :] (차원추가)

In [147]:
a = np.arange(1,5)
print(a)
print('---------')
a = a[np.newaxis, :]
print(a)

[1 2 3 4]
---------
[[1 2 3 4]]


# 11 : Operation b/t arrays  (사칙연산)

- numpy 는 array 간 기본적인 사칙 연산을 지원함  
    = Element-wise operation

    - \+ : 덧셈

    - \- : 뺄셈

    - \* : 곱셈

    - \** : 제곱

    - / : 나눗셈

    - // : 몫

    - % : 나머지

        - 예시

            <img src='../image/numpy_09.jpeg' width=400>

# 12 : Dot product (내적)

In [149]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(3,2)

In [150]:
a.dot(b)

array([[ 58,  64],
       [139, 154]])

In [151]:
np.dot(a,b)

array([[ 58,  64],
       [139, 154]])

# 13 : Transpose (전치 행렬)

In [152]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [153]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [154]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [156]:
np.dot(a.T, a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

# 14 : boardcasting

- shape 이 다른 배열간 연산을 지원하는 기능

    <img src='../image/numpy_10.jpeg' width=350>

## -01 : EX_01

In [172]:
a = np.arange(1,7).reshape(2,3)
b = np.array(3)

print('a\n',a,'\n----------')
print('b\n',b,'\n----------')
print('a+b\n',a+b)

a
 [[1 2 3]
 [4 5 6]] 
----------
b
 3 
----------
a+b
 [[4 5 6]
 [7 8 9]]


In [173]:
a + 3

array([[4, 5, 6],
       [7, 8, 9]])

In [174]:
a // 2

array([[0, 1, 1],
       [2, 2, 3]])

## -02 : EX_02 (broadcasting 응용)

<img src='../image/numpy_11.jpeg' width=600>

### Case #1

In [192]:
a = np.arange(3)
a = a[np.newaxis, :]
a = np.concatenate((a,a,a,a), axis=0)
print(a)
print('------')

b = np.arange(0, 31, 10)
b = b[np.newaxis, :]
b = b.T
b = np.concatenate((b,b,b), axis=1)
print(b)
print('------')

print(a+b)

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]
------
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
------
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


### Case #2

In [193]:
a = np.arange(3)
print(a)
print('------')

b = np.arange(0, 31, 10)
b = b[np.newaxis, :]
b = b.T
b = np.concatenate((b,b,b), axis=1)
print(b)
print('------')

print(a+b)

[0 1 2]
------
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
------
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


### Case #3

In [196]:
a = np.arange(3)
print(a)
print('------')

b = np.arange(0, 31, 10)
b = b[np.newaxis, :]
b = b.T
print(b)
print('------')

print(a+b)

[0 1 2]
------
[[ 0]
 [10]
 [20]
 [30]]
------
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


# 15 : Numpy Performance #1 (timeit)

- timeit : jupyter 환경에서 코드의 퍼포먼스를 체크하는 함수

In [204]:
def scalar_vector_product(scalar, vector) :
    result = []
    for value in vector :
        result.append(scalar * value)
    return result

iternation_max = 1000000

vector = list(range(iternation_max))
scalar = 2

In [205]:
%timeit scalar_vector_product(scalar, vector)                   # for loop을 이용한 성능

91.8 ms ± 489 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [206]:
%timeit [scalar * value for value in range(iternation_max)]     # list comprehension 을 이용한 성능

63.6 ms ± 222 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [207]:
%timeit np.arange(iternation_max) * scalar                      # numpy 를 이용한 성능

1.03 ms ± 5.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


# 16 : Numpy performance #2

- 일반적인 속도  
    for loop < list comprehension < numpy

- 100,000,000 번의 loop 이 돌때, 약 4배 이상의 성능 차이를 보임

- numpy 는 C 로 구현되어 있어, 성능을 확보하는 대신 Python 의 가장 큰 특징인 dynamic typing 을 포기함

- 대용량 계산에서는 가장 흔히 사용됨

- Conceatenate 처럼 계산이 아닌, 할당에서는 연산 속도의 이점이 없음

# 17 : Comparison (비교)

## -01 : boolean array

In [208]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [209]:
a < 4

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [211]:
a < 10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## -02 : All & Any

- Array 의 데이터 전부(and) 또는 읿부(or) 가 조건에 만족 여부 반환

In [212]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### _01 : any ( 하나라도 만족 시 : True )

In [214]:
# 하나라도 True 인지
    # ex. [True, False] -> True
np.any(a>5)

True

### _02 : all ( 모두 만족 시 : True )

In [217]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [215]:
np.all(a>5)

False

In [218]:
a < 10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [216]:
np.all(a<10)

True

### _01 : comparision operation EX #1

- numpy 는 배열의 크기가 동일할 때  
    element 간 결과를 boolean typoe 으로 반환

In [219]:
a = np.array([1, 3, 0], float)
b = np.array([5, 2, 1], float)

array([False,  True, False])

In [220]:
print( a > b )
print( (a > b).any() )

print( a == b )
print( (a == b).all() )

[False  True False]
True
[False False False]
False


### _02 : comparision operation EX #2

#### logical_and

In [221]:
a = np.array([1, 3, 0], float)
np.logical_and( a > 0, a < 3)   # and 조건의 condition

array([ True, False, False])

#### logical_not

In [226]:
b = np.array([True, False, False], bool)
np.logical_not(b)   # not 조건의 condition (False 인지 아닌지) -> 반대로 출력

array([False,  True,  True])

#### logical_or

In [227]:
c = np.array([False, True, False], bool)
np.logical_or(b,c)  # or 조건의 condition (b 또는 c 중에 True 가 있는지)

array([ True,  True, False])

# 18 : np.where

## -01 : set value

> np.where( condition, True_value, False_value)

In [229]:
a

array([1., 3., 0.])

In [228]:
np.where(a > 0, 3, 2)

array([3, 3, 2])

## -02 : return index number
> np.where(condition)

In [232]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [233]:
np.where(a > 5)

(array([6, 7, 8, 9]),)

## -03 : np.isnan( ) : 결측치 찾기

- isnan : Not a Number

In [234]:
a = np.array([1, np.NaN, np.Inf], float)
a

array([ 1., nan, inf])

In [235]:
np.isnan(a)

array([False,  True, False])

## -04 : np.isfinite( ) : 무한값 찾기

- isfinite : finite number

In [236]:
a

array([ 1., nan, inf])

In [237]:
np.isfinite(a)

array([ True, False, False])

# 19 : arg

- array 내 최대값 또는 최소값의 index 를 반환
    - argument max
        > np.argmax( )
    - argument min
        > np.argmin( )

- axis 기반의 반환
    > np.argmax(a, axis = )

## -01 : argmin & argmax

In [238]:
a = np.array([1,2,4,5,8,78,2,33])
np.argmax(a), np.argmin(a)

(5, 0)

## -02 : arg - axis 지정 (2차원 이상)

In [239]:
a = np.array([[1,2,4,7], [9,88,6,45], [9,76,3,4]])
print(a)
print('--------')
np.argmax(a, axis=1), np.argmin(a, axis=0)

[[ 1  2  4  7]
 [ 9 88  6 45]
 [ 9 76  3  4]]
--------


(array([3, 1, 1]), array([0, 0, 2, 2]))

## -03 : argsort

- sorting(오름차순) 후 원래의 index번호 반환

In [240]:
a = np.array([1,2,3,4,5,8,78,23,3])
a

array([ 1,  2,  3,  4,  5,  8, 78, 23,  3])

In [241]:
a.argsort()

array([0, 1, 2, 8, 3, 4, 5, 7, 6])

## -04 : [::-1] 역순으로 반환 

In [242]:
a.argsort()[::-1]

array([6, 7, 5, 4, 3, 8, 2, 1, 0])

## -05 : 활용법

In [243]:
a[np.argmax(a)]

78

# 20 : Boolean Index

- 특정 조건에 따른 값을 배열 형태로 추출

- Comparision operation 함수들도 모두 사용가능

## -01 : EX #1

In [244]:
a = np.array([1, 4, 0, 2, 3, 8, 9, 7], float)
a > 3

array([False,  True, False, False, False,  True,  True,  True])

In [246]:
a[a>3]  # 조건이 True 인 element 만 추출

array([4., 8., 9., 7.])

## -02 : EX #2

In [248]:
condition = a < 3
a[condition]

array([1., 0., 2.])

## -03 : EX #3

In [253]:
a[np.array([True, True, False, False, False, False, False, True], bool)]

array([1., 4., 7.])

# 21 : Fancy Index

- numpy 는  array 를 index value 로 사용해서 값 추출

## -01 : EX #1 (basic)

In [258]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)   # 반드시 int 로 선언

a[b]    # bracket index, b 배열의 값을 indeX로 gkdu a 의 값들을 추출함 

array([2., 2., 4., 8., 6., 4.])

## -02 : EX #2 (take func)

In [256]:
a.take(b)   # take 함수 : bracket index 와 같은 효과

array([2., 2., 4., 8., 6., 4.])

## -03 : EX #3 (matrix type)

In [260]:
a = np.array([[1,4], [9,16]])
b = np.array([0,0,1,1,0], int)
c = np.array([0,1,1,1,1], int)

In [273]:
a[b]

array([[ 1,  4],
       [ 1,  4],
       [ 9, 16],
       [ 9, 16],
       [ 1,  4]])

In [263]:
a[b,c]  # b = axis0 = row / c = axis1 = col 

array([ 1,  4, 16, 16,  4])

In [265]:
a.take(b, axis=0).take(c, axis=1)

array([[ 1,  4,  4,  4,  4],
       [ 1,  4,  4,  4,  4],
       [ 9, 16, 16, 16, 16],
       [ 9, 16, 16, 16, 16],
       [ 1,  4,  4,  4,  4]])

# 22 : Numpy Data I/O

## -01 : Loadtxt & savetxt

In [274]:
# 예제 파일이 없음....